server:
  port: 8089
  servlet:
    context-path: /rememberme
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2957558313@qq.com
    password: zmecmqbfkqsrddec
    from: 2957558313@qq.com
    properties.mail.smtp.ssl.enable: true
  redis:
    port: 6379
    database: 0
    host: 10.10.10.18
mybatis:
  mapper-locations: classpath:/Mapper/*.xml
salt: rememberme
defaultuserimg: https://dss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1155785496,4012400290&fm=26&gp=0.jpg
hashcount: 50
